# Generated by Django 4.0 on 2021-12-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='invited_count',
            field=models.IntegerField(default=0, verbose_name='Количество приглашенных пользователей'),
        ),
    ]
