# Generated by Django 4.0 on 2021-12-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_botuser_remove_pairrequest_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='user_timezone',
        ),
    ]
