# Generated by Django 4.0 on 2021-12-30 21:23

import base.classes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_remove_botuser_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='sex',
            field=models.CharField(choices=[('GIRL', 'Женщина'), ('MALE', 'Мужчина')], default='MALE', max_length=32, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='UserSupportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(verbose_name='Вопрос')),
                ('answer_body', models.TextField(verbose_name='Ответ')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('ANSWERED', 'Отвечен')], default='CREATED', max_length=32, verbose_name='Статус')),
                ('type', models.CharField(choices=[('CLIENT', 'Клиентская'), ('TECHNICAL', 'Техническая'), ('PERSONAL_MANAGER', 'Персональный менеджер'), ('PARTNERSHIP', 'Сотрудничество')], default='CLIENT', max_length=32, verbose_name='Тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user_accounts.botuser', verbose_name='Пользователь')),
            ],
            bases=(base.classes.DjangoModelAutoStr, models.Model),
        ),
    ]
