# Generated by Django 4.0 on 2021-12-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_alter_botuser_sex_usersupportquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Является ли админом'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='sex',
            field=models.CharField(choices=[('GIRL', 'Женщина'), ('MALE', 'Мужчина'), ('UNKNOWN', 'Не установлен')], default='UNKNOWN', max_length=32, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='usersupportquestion',
            name='answer_body',
            field=models.TextField(blank=True, default='', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='usersupportquestion',
            name='question_body',
            field=models.TextField(blank=True, default='', verbose_name='Вопрос'),
        ),
    ]
