# Generated by Django 4.0 on 2022-01-04 20:54

import base.classes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_country'),
        ('user_accounts', '0006_botuser_is_admin_alter_botuser_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('FILLED', 'Заполнен'), ('CONFIRMED', 'Подтвержден'), ('REJECTED', 'Отклонен'), ('DELETED', 'Удален')], default='CREATED', max_length=32)),
                ('first_name', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('body_params', models.CharField(max_length=64)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='location.country')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nationalities', to='location.country')),
            ],
            bases=(base.classes.DjangoModelAutoStr, models.Model),
        ),
        migrations.CreateModel(
            name='GirlProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_vip_status', models.BooleanField(default=False, verbose_name='Есть вип статус')),
                ('has_top_status', models.BooleanField(default=False, verbose_name='Есть топ статус')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='girl_profile', to='user_accounts.botuser')),
            ],
            options={
                'abstract': False,
            },
            bases=(base.classes.DjangoModelAutoStr, models.Model),
        ),
        migrations.CreateModel(
            name='GirlFormPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve', models.BooleanField(default=False, verbose_name='Для подтверждения')),
                ('photo', models.ImageField(upload_to='girl_photo/', verbose_name='Фото')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user_accounts.girlform', verbose_name='Форма')),
            ],
            bases=(base.classes.DjangoModelAutoStr, models.Model),
        ),
        migrations.AddField(
            model_name='girlform',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_accounts.girlprofile'),
        ),
    ]
