# Generated by Django 4.0 on 2022-01-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_country'),
        ('user_accounts', '0007_girlform_girlprofile_girlformphoto_girlform_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='inviting_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='user_accounts.botuser', verbose_name='Пригласивший пользователь'),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='body_params',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='location.country'),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nationalities', to='location.country'),
        ),
        migrations.AlterField(
            model_name='girlform',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
