# Generated by Django 4.0 on 2022-01-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_alter_botuser_inviting_user_alter_girlform_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girlform',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='user_accounts.girlprofile'),
        ),
    ]
