# Generated by Django 4.0 on 2022-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_alter_girlform_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlform',
            name='documents',
            field=models.TextField(blank=True, default='', verbose_name='Имеющиеся документы'),
        ),
        migrations.AddField(
            model_name='girlform',
            name='short_dates',
            field=models.BooleanField(default=False),
        ),
    ]
