# Generated by Django 4.0 on 2022-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_girlform_documents_girlform_short_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girlform',
            name='age',
        ),
        migrations.RemoveField(
            model_name='girlform',
            name='body_params',
        ),
        migrations.RemoveField(
            model_name='girlform',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='girlform',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='girlform',
            name='height',
        ),
        migrations.RemoveField(
            model_name='girlform',
            name='short_dates',
        ),
        migrations.RemoveField(
            model_name='girlform',
            name='weight',
        ),
        migrations.AddField(
            model_name='girlform',
            name='aditional_data',
            field=models.JSONField(default={}, verbose_name='Дополнительные данные'),
        ),
    ]
