# Generated by Django 4.0 on 2022-01-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_remove_girlform_age_remove_girlform_body_params_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girlform',
            old_name='aditional_data',
            new_name='additional_data',
        ),
    ]
