# Generated by Django 4.0.1 on 2022-01-11 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0014_remove_girlprofile_has_top_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='girlform',
            name='additional_data',
            field=models.JSONField(blank=True, default={}, verbose_name='Дополнительные данные'),
        ),
    ]
