# Generated by Django 4.0.1 on 2022-01-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0015_girlform_created_at_alter_girlform_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girlformphoto',
            name='photo',
            field=models.FileField(upload_to='girl_photo/', verbose_name='Фото'),
        ),
    ]
