# Generated by Django 4.0.1 on 2022-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0016_alter_girlformphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='telegram_meta',
            field=models.JSONField(default=dict, verbose_name='Метаданные tg'),
        ),
    ]
