# Generated by Django 4.0.1 on 2022-01-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0017_botuser_telegram_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girlform',
            name='nationality',
        ),
    ]
