# Generated by Django 4.0 on 2022-01-10 04:21

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0009_alter_girlform_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('APPROVED', 'Подтвержден'), ('REJECTED', 'Отклонен')], default='CREATED', max_length=32)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=17, verbose_name='Сумма оплаты')),
                ('screenshot', models.ImageField(upload_to=payment.models.get_screenshot_image_path, verbose_name='Скрин')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_accounts.botuser', verbose_name='Пользователь')),
            ],
        ),
    ]
